### ISSUE TITLE
unnecessary log line

### ISSUE THREAD

**Issue by MithrilMan** [stratisproject/FederatedSidechains#303]
this line is unnecessary as Fody already print this

https://github.com/stratisproject/FederatedSidechains/blob/208571a9aecfde8c0494410da2b120854cd56070/src/Stratis.FederatedPeg.Features.FederationGateway/TargetChain/CrossChainTransferStore.cs#L950

this causes the log to have a duplication as

```
2018-12-15 19:59:19.6578||53||TRACE||Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.Put||(-)||||CrossChainTransferStore.Synchronize => CrossChainTransferStore.SynchronizeBatch => CrossChainTransferStore.Put
2018-12-15 19:59:19.6578||53||TRACE||Stratis.FederatedPeg.Features.FederationGateway.TargetChain.CrossChainTransferStore.Put||(-)||||CrossChainTransferStore.Synchronize => CrossChainTransferStore.SynchronizeBatch => CrossChainTransferStore.Put
```

**Comment by MithrilMan** [comment]
searching in the code for `this.logger.LogTrace("(-)` shown lot of unnecessary log entry to remove

**Comment by bokobza** [comment]
Fixed in #304

**Comment by MithrilMan** [comment]
it's partially fixed, I'd leave this issue open 'till we remove all explicit Traces
